version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank_card_db
    restart: always
    environment:
      POSTGRES_DB: bank_card_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1493041
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bank_card_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: card-management-system
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bank_card_db:5432/bank_card_db?currentSchema=banksystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1493041
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: banksystem
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/changelog-master.xml
      SPRING_LIQUIBASE_DEFAULT_SCHEMA: banksystem
      SPRING_LIQUIBASE_USERNAME: postgres
      SPRING_LIQUIBASE_PASSWORD: 1493041
      JWT_SECRET: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
      JWT_LIFETIME: 10m
      CARD_ENCRYPTION_KEY: my-32-character-super-secret-key-1234
      CARD_ENCRYPTION_ALGORITHM: AES
    volumes:
      - ./logs:/app/logs

volumes:
  pgdata: